### ISSUE TITLE
User should be warned when an existing command is about to be overwritten

### ISSUE THREAD

**Issue by javatarz** [the-lazy-devs/custom_commands#15]
## Narrative

AS A user
I WANT to be warned about commands over writing existing system commands
SO THAT I can choose the commands being installed and not lose critical system functionality

### 1. Existing functionality (BAU)

```
GIVEN a system command $c
  and a custom command to be installed $d
WHEN  the custom command is about to be installed
THEN  no conflict messages should be seen
```
### 2. Prompt user for conflicting command installation

```
GIVEN a system command $c
  and a custom command to be installed $c
WHEN  the custom command is about to be installed
THEN  the user should be warned about the conflict
  and the user should be asked if they would like to continue the installation, skip this custom command, abort the entire installation or revert and abort the installation
```
### 3. Overwriting system command (Continue action)

```
GIVEN the user is about to install a conflicting command
  and the user is prompted for their choice of action
WHEN  the user chooses to continue the installation of the custom command
THEN  the symlink for the command should be installed (symlink is created in ~/.bin)
  and the user should be able to use the installed command from the shell instead of the system command
  and the program should continue
```
### 4. Skipping custom command installation

```
GIVEN the user is about to install a conflicting command
  and the user is prompted for their choice of action
WHEN  the user chooses to skip the installation of the custom command
THEN  the symlink for the command should not be installed (no symlink created in ~/.bin)
  and the user should be able to use the system command from the shell
  and the program should continue
```
### 5. Aborting custom command installation

```
GIVEN the user is about to install a conflicting command
  and the user is prompted for their choice of action
WHEN  the user chooses to abort the installation of the custom command
THEN  the symlink for the command should not be installed (no symlink created in ~/.bin)
  and the program should exit
```
### 6. Reverting custom command installation

```
GIVEN the user is about to install a conflicting command
  and the user is prompted for their choice of action
WHEN  the user chooses to revert the installation of the custom command
THEN  the symlink for the command should not be installed (no symlink created in ~/.bin)
  and the symlinks which were installed by the script in the existing installation should be removed
  and the program should exit
```

**Note**: Recommended that AC-6 should be split into it's own card.

**Comment by binkley** [comment]
@JAnderton could have a better Persona than `user`.  :)

Also, "SO THAT": does that imply that I would be given an opportunity to rename commands on installation, after suitable warning of a conflict?

**Comment by JAnderton** [comment]
@binkley: Mea culpa. Meesa was lazy.

Does `developer using command line aliases on a unix machine` sound better?

**Comment by spargonaut** [comment]
Is this functionality really a thing?
i.e. with the current functionality, we're adding the reference to the symlink directory at the end of the PATH variable. If I create a custom command called find.sh, its not going to overwrite access to the 'find' command that comes with the system because the system find is going to be found first.

I'm thinking we might want to print out a message saying that the custom command won't work because of this behavior (AC #2), and encourage the user to rename their custom command.

thoughts?

**Comment by javatarz** [comment]
I agree. Warn the user. Ignore the other use cases. System defaults always win followed by things the script is about to add to path followed by aliases. In that order.

**Comment by spargonaut** [comment]
ok.  I'm planning (hoping) to write a script that describes whats either in a custom command, or opens the man page for you (if its not the users custom command).  I think the functionality of that script (or at least my vision of it) would have a lot of the same functionality that we would want here.  I'm sure I'll make some noise when I've got something to look at.

**Comment by spargonaut** [comment]
I'm closing this issue b/c its not really a thing.
command collisions are totally a thing though, so I'll add a new issue as an enhancement.

maybe.
